spring:
  application:
    name: quartz-test

  datasource:
    url: jdbc:postgresql://postgres-quartz-test:5432/umpa
    username: admin
    password: 123
    driver-class-name: org.postgresql.Driver