app:
  name: quifKa

server:
  port: 8787

spring:
  application:
    name: quartz-test
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            dataSource: quartzDataSource2
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            misfireThreshold: 4000
            # ввел динамически в config
#          threadPool:
#            threadCount: 1

schedule:
  jobs:
    #    hello:
    #      cron: "32 * * * * ?"
    #      #          cron: "-"
    test2:
      cron: "0/5 * * * * ?"
    sample:
      cron: "0/30 * * * * ?"
    #      cron: "-"
#    bye:
#      cron: "0/5 * * * * ?"
