server:
  port: 8787

spring:
  application:
    name: quartz-test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
  quartz:
    data-source: quartzDataSource
    job-store-type: jdbc
    jdbc:
      initialize-schema: always #embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
#            instanceName: QuartzScheduler
          jobStore:
            dataSource: quartzDataSource2
            class: org.quartz.impl.jdbcjobstore.JobStoreTX #не включать!
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            misfireThreshold: 4000
             # ввел ручками динамически в config
#          threadPool:
#            threadCount: 1

schedule:
  jobs:
#    hello:
#      cron: "32 * * * * ?"
#      #          cron: "-"
    test2:
      cron: "0/5 * * * * ?"
    sample:
      cron: "0/30 * * * * ?"
    #      cron: "-"
#    bye:
#      cron: "0/5 * * * * ?"
